### ISSUE TITLE
Better project name?

### ISSUE THREAD

**Issue by TaiAurori** [pablouser1/ProxiTok#1]
This is the first frontend I've ever seen for TikTok so far (great job on it), and having a more recognizable name would help for visibility.

**Comment by pablouser1** [comment]
Yeah, you're right. The current name is really generic. I've been developing the program without thinking much about it. But it would still be really nice having a good name. I don't have any name in mind though, so any suggestions are welcome.

**Comment by ltGuillaume** [comment]
So toktok is a delivery app, too bad.

proxtok? tikprox?

**Comment by mendel5** [comment]
How about ProxiTok?

**Comment by pablouser1** [comment]
> How about ProxiTok?

Really liked it, I'm probably changing the name to the project to this
