### ISSUE TITLE
Pictures?

### ISSUE THREAD

**Issue by MintMain21** [pablouser1/ProxiTok#100]
**Is your feature request related to a problem? Please describe.**
Apparently Tik Tok can be used to share static images (pictures) instead of just video, but it's exclusive to the app, so not only do you get an error message in ProxiTok, you get a "use the app" prompt in actual Tik Tok.

**Describe the solution you'd like**
If we cannot get picture support, then at the very least it would be nice to have an explanation for why pictures can't be displayed, instead of leaving a vague error code that would point people to try actual Tik Tok anyway.

**Comment by NoPlagiarism** [comment]
@MintMain21 Can you send an example link, pls?

**Comment by MintMain21** [comment]
https://www.tiktok.com/t/ZTRQs6X6s/

**Comment by pablouser1** [comment]
So, investigating a little bit about it, turns out TikTok returns a 404 error even though it _technically_ exists. That's why it just showed a "Not found" error.

I've patch it with pablouser1/TikScraperPHP@2b5f7f4aa436ec7a9727ec35396becee211135da, now it shows an IMAGE_NOT_SUPPORTED error, which I guess is more informative than before.

I haven't investigated about implementing pictures in Proxitok though... It involves using the mobile API which is way harder to reverse engineer than the web one. Maybe some day I'll investigate it, but I don't really have time right now.

**Comment by NomarCub** [comment]
Actually, you probably don't need the mobile API for this @pablouser1. One image I tried displays the same error on desktop web TikTok, but plays the "gallery" as a video on a mobile browser, even without logging in.
The link in the previous reply is now private, here's one I used for testing that's still up: [link](https://www.tiktok.com/@heart.eyes.4him_/video/7173636856242785537)

**Comment by NoPlagiarism** [comment]
Btw, now, when some User-Agents has been changed to mobile, [it displays first picture of gallery on preview](https://proxitok.pabloferreiro.es/@heart.eyes.4him_/video/7173636856242785537)

**Comment by NomarCub** [comment]
The link I posted, and pictures / "gallery posts" in general are available in the desktop browser now.

**Comment by pablouser1** [comment]
Hi, this has been implemented with commit 33c723d786551e12b30cdb8f675d1c8a29e827fa. For example, the pictures that @NoPlagiarism sent now looks like this:
![image](https://user-images.githubusercontent.com/17802865/229293681-41fbf373-5dd6-472d-92e7-d4b171dd43cf.png)

It doesn't look that good at the moment, I'm currently implementing a CSS-only carousel which will improve the UI.

> https://gist.github.com/Kylianalex/0bd35e40ac07591119393cc0daeecffb hope this can help

This method does work but is not really future-proof, the css can be changed anytime. The images can be extracted from SIGI_STATE from the `imagePost` attribute.

**Comment by pablouser1** [comment]
The carousel is now implemented, it looks like this:
![carousel](https://user-images.githubusercontent.com/17802865/229297438-7076b124-1e15-44bf-9fb7-ed514c4a18b5.png)
