### ISSUE TITLE
Show larger profile image on a user profile page

### ISSUE THREAD

**Issue by TrashAccount3424** [pablouser1/ProxiTok#102]
**Is your feature request related to a problem? Please describe.**

Show larger profile image on a user profile page.
For example on https://proxitok.pabloferreiro.es/@tiktok the top image is just 100x100 pixels.
Tiktok does seem to provide larger images.

`https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/1971e99be0d67160f34f39fb1d66a0e5~c5_720x720.jpeg?x-expires=16693.....`
See file name > 720x720.jpeg.

---
**Describe the solution you'd like**
Increase the profile header image size so the content can be seen rather than just a thumbnail of it.

---
**Describe alternatives you've considered**
Maybe a download button for full size image would be an alternative.

**Comment by pablouser1** [comment]
Hi! Thanks to ce5c9e016bd10807969f4602dc45bca58892acbe the user's page now show the avatarLarger attribute instead, now it looks way sharper, thanks for the recommendation!

**Comment by TrashAccount3424** [comment]
> Hi! Thanks to [ce5c9e0](https://github.com/pablouser1/ProxiTok/commit/ce5c9e016bd10807969f4602dc45bca58892acbe) the user's page now show the avatarLarger attribute instead, now it looks way sharper, thanks for the recommendation!

Awesome, much appreciated 👍
