### ISSUE TITLE
Can't download videos on iOS

### ISSUE THREAD

**Issue by Lignite4** [pablouser1/ProxiTok#104]
**Describe the bug**

In the new version, to download videos, you need to hover over the download button to see the download options. 

iOS browsers do not support this feature. 

To fix this, change it, so instead of hovering the mouse over the download button, you need to press the download button to display the download options. Like in old versions. 

It would also be nice to work without JavaScript.

**To Reproduce**
Press download in Safari on iOS

**Expected behavior**
Should download video

**Comment by pablouser1** [comment]
Fixed with 89d9ad2f9ccf3dd21367d4cb3e33690476baaaa7, now the elements are more mobile-friendly
