### ISSUE TITLE
user video next button is not showing.

### ISSUE THREAD

**Issue by salman731** [pablouser1/ProxiTok#105]
When I searched user then at end of page next button is not showing. Please fix it.

**Comment by NoPlagiarism** [comment]
It's kinda a duplicate of #94

You can't see next button, because ProxiTok can't get next page

**Comment by salman731** [comment]
> It's kinda a duplicate of #94
> 
> You can't see next button, because ProxiTok can't get next page

It was working some days ago but now it is not working...

**Comment by NoPlagiarism** [comment]
What was working exactly? "Next" button or next page?

Next page - #94

Next button is not showing, because it can't see next page

**Comment by NoPlagiarism** [comment]
@salman731 are u going to close issue or you have other questions?
