### ISSUE TITLE
Using VideoID causes 403 error

### ISSUE THREAD

**Issue by BrodieRobertson** [pablouser1/ProxiTok#11]
Upon searching for a videoID or going directly to a video page, I am presented with this.

![2022-02-14_11-16](https://user-images.githubusercontent.com/30792656/153783067-151d53ad-8ea3-49fd-8adc-6a74e45c4cd3.png)

Going to a creators page and watching the same video works just fine.

**Comment by pablouser1** [comment]
Hello, this looks exclusive to Heroku, I can't replicate it locally. I'm investigating this issue.

I have also reverted the official instance to an older version that does work.

**Comment by pablouser1** [comment]
Looks like this has already been fixed. At least I haven't had any issues with this anymore. I'll close this issue, if this still happens please reopen this issue or create a new one.
