### ISSUE TITLE
[Bug] [UI] Post buttons sometimes unusable on mobile

### ISSUE THREAD

**Issue by KaKi87** [pablouser1/ProxiTok#119]
**Describe the bug**
On mobile, *Share* & *Download* buttons create scroll in the post item because of the dropdown appearing.
Sometimes, the user only have to scroll down to be able to use the dropdown, which is just bad experience.
But sometimes, the user can't use the buttons at all, because the dropdown disappears as soon as it appears, the scrollbar putting the button out of focus.

**To Reproduce**
1. Open ProxiTok on mobile
2. Try clicking the *Share* or *Download* buttons
3. Notice unusability (or bad experience)

**Expected behavior**
The buttons are usable and provide good experience, i.e. the dropdown should not create a scroll area, or another solution should be used instead (e.g. modal, or just 4 links instead of 2 buttons hiding 2 links each).

**Logs**
![](https://user-images.githubusercontent.com/21284089/212792359-e7f5dabb-270e-4795-af25-a43187064b17.gif)

**Enviroment (please complete the following information):**

- Deployment method (if possible): Unknown
- Frontend version: [2.4.3.6
- Scrapper version: 2.3.3.1
- PHP Version: Unknown

---

Thanks

**Comment by pablouser1** [comment]
Fixed with 89d9ad2f9ccf3dd21367d4cb3e33690476baaaa7, now the elements are more mobile-friendly

**Comment by KaKi87** [comment]
Thanks !

Usable but still a bit weird though :

![](https://cdn.discordapp.com/attachments/723185786794803252/1067861443321532436/Screenshot_20230125-183929_Kiwi_Browser-01.jpeg)

Also, if I didn't remember the old UI, I wouldn't guess that "WM" means "watermark", I would like to suggest keeping using the whole word.

However, I'd like to suggest using a checkbox instead of a dropdown.

Thanks

**Comment by KaKi87** [comment]
Actually, there's a more important drawback to this new UI : I can no longer copy the download URL as it's generated by JS, nor use Android's *share* feature on it.

Thanks

**Comment by pablouser1** [comment]
Thanks for the heads up! Now it looks like this (Tested on a Pocophone F1)
![Screenshot_20230125-210741_Mull](https://user-images.githubusercontent.com/17802865/214678424-c66f2f02-baf5-42a4-a217-80023a09b87f.png)

You can both click your prefered option on mobile and copy the url if you want. There are some issues on some smaller-screens with overflow, I'll try to fix it

**Comment by KaKi87** [comment]
That works too.
On which release will this be ?
Thanks

**Comment by pablouser1** [comment]
Implemented on v2.4.4.3
