### ISSUE TITLE
Pages has no videos on them after clicking "Next"

### ISSUE THREAD

**Issue by airikr-e** [pablouser1/ProxiTok#12]
If you go to a tag, for an example (funnyvideos)[https://proxitok.herokuapp.com/tag/funnyvideos], you'll see videos. But if you hit the "Next" button, the next page will not have any videos at all and the "Next" button are inactive yet clickable (just reloads the page). (This link)[https://proxitok.herokuapp.com/tag/funnyvideos?cursor=5854611] shows this.

If you're on the trending page, you can get more videos on the first next page click, but not if you click on it again.

**Comment by pablouser1** [comment]
This is an issue with the old Wrapper. It will be fixed with the new Wrapper being developed  on the new-api branch.

**Comment by pablouser1** [comment]
The new Api Wrapper is already finished and it fixes this issue, although the official instance still uses the legacy api because TikTok blocks the IP from the server that is hosting it. You can use another public instance or host your own instance.
