### ISSUE TITLE
Add Username and Password environment variables to access your ProxiTok Link

### ISSUE THREAD

**Issue by mariushosting** [pablouser1/ProxiTok#121]
It would be a great idea to have ProxiTok access protected by password.
2 Environment variables for username and password.

**Comment by pablouser1** [comment]
Hey, I find redundant to implement this, it can already be achieved at server-level using [Apache](https://www.cyberciti.biz/faq/howto-setup-apache-password-protect-directory-with-htaccess-file/)/[Nginx](https://www.cyberciti.biz/faq/nginx-password-protect-directory-with-nginx-htpasswd-authentication/) password protected directories. The webmaster can change his own config if he wants his instance to be password protected
