### ISSUE TITLE
[INSTANCES] New public instance

### ISSUE THREAD

**Issue by hardcore-sushi** [pablouser1/ProxiTok#122]
- URL: https://tok.thekitty.zone
- Cloudflare: No
- Country: Germany

Hosted by @11Tuvork28

**Comment by pablouser1** [comment]
Thanks @11Tuvork28 for hosting a public instance! I have added it to the public instances list.

**Comment by 11Tuvork28** [comment]
Thanks for adding my instance to the list!

**Comment by 11Tuvork28** [comment]
@pablouser1 Please remove the instance, as its going offline due to personal life things.

**Comment by pablouser1** [comment]
Sure, it is now removed.
