### ISSUE TITLE
[Feature Request] Data API

### ISSUE THREAD

**Issue by nanometer5088** [pablouser1/ProxiTok#123]
I'm doing a project to download / stream tiktok from my own software.

Right now, I'm using ProxiTok RSS feed to get info such as links. Problem is, this limits my software only to the latest 30 videos, both trending and a user profile.

Would it be possible to have API endpoints on Proxitok that could provide full information?

**Comment by pablouser1** [comment]
Hi, it is indeed posible but is not one of the objectives of this project. You should use a scraper library like the following:
* [TikTok-Api](https://github.com/davidteather/TikTok-Api) for Python
* [tiktok-scraper](https://github.com/drawrowfly/tiktok-scraper) for Typescript
* [TikScraperPHP](https://github.com/pablouser1/TikScraperPHP) for PHP (this is the same scraper that is used on this project)

You should be able to make all the requests without having to worry about those limitations.
