### ISSUE TITLE
Private account detected! Not supported

### ISSUE THREAD

**Issue by TrashAccount3424** [pablouser1/ProxiTok#124]
**Is your feature request related to a problem? Please describe.**
Private accounts give an error page.
```
There was an error processing your request!
HTTP Code: 401
Private account detected! Not supported
```

**Describe the solution you'd like**
Private accounts have public profile with following/likes count and profile image. It would be great if the normal profile page would load instead of the error page. 

**Describe alternatives you've considered**
¯\\_(ツ)_/¯

**Comment by pablouser1** [comment]
Thanks for the improvement suggestion! It has been implemented with 5dea2468f821cb2e29a0d31c926f314cbcc06055.There really wasn't a reason for having that error, so now it's removed. Now if the account is private it just tells you about it.
