### ISSUE TITLE
Git folder exposed

### ISSUE THREAD

**Issue by RoyTakanen** [pablouser1/ProxiTok#128]
**Describe the bug**
The http server leaks `.git`-folder to everyone accessing the ProxiTok instance. This can be avoided by adding it to [.dockerignore](https://github.com/pablouser1/ProxiTok/blob/master/.dockerignore). There is also a little chance that secrets are exposed if `.git/config` file has them. 

Example:

```
[http "https://github.com/"]
	extraheader = AUTHORIZATION: basic [REDACTED]
```

Commit `288f87504c252b9bd6293f57d910f92ec06d716b` in https://github.com/pablouser1/ProxiTok/pull/125 fixes this (see the changes [here](https://github.com/pablouser1/ProxiTok/pull/125/commits/288f87504c252b9bd6293f57d910f92ec06d716b)). 

**To Reproduce**
1. Go to almost any working ProxiTok instance and make sure that the path is `/.git/config`
2. See the exposed git config

**Expected behavior**
The folder should not be exposed

**Comment by pablouser1** [comment]
Thanks for the heads-up! I didn't even noticed, it's being merged with #125
