### ISSUE TITLE
API error code -1 (UNKNOWN_ERROR)

### ISSUE THREAD

**Issue by txhno** [pablouser1/ProxiTok#129]
- [URL: https://proxitok.example.com](https://proxitok.pabloferreiro.es/)
- Cloudflare: Yes
- Country: India

There was an error processing your request!

HTTP Code: 503

API error code -1 (UNKNOWN_ERROR) [What does this mean?](https://proxitok.pabloferreiro.es/verify)

Always giving this error.

**Comment by NoPlagiarism** [comment]
1. It only when you try to search users?
2. If yes, relatable to #94
3. Try searching [another instance](https://github.com/pablouser1/ProxiTok/wiki/Public-instances). For example, [tt.vern.cc](https://tt.vern.cc/)

**Comment by pablouser1** [comment]
Looks like, at least for me, is User-Agent related, changing the user agent fixes it. #125 is currently working on supporting custom user agents for moments like this.

**Comment by txhno** [comment]
Hey, it fixed when I used another instance.

**Comment by xbdmHQ** [comment]
The issue is fixed, They probably are using the same port by mistake. Try mines, Which i requested to be on the public instance list: https://cringe.xbdm.fun (Everything works too)
