### ISSUE TITLE
[INSTANCES] New public instance + instance maintenance

### ISSUE THREAD

**Issue by Exonip** [pablouser1/ProxiTok#130]
- URL: https://proxitok.privacy.com.de 
- Cloudflare: No
- Country: Germany

Also tested all public instances. https://proxitok.mha.fi/ by @NyeUsr  returned 502 and was down.
https://proxitok.marcopisco.com/  by @marcoapisco was only online due to cloudflare "always online" (no content loaded)

**Comment by pablouser1** [comment]
Hi @Exonip, thanks for the info! The new instance has been added and the broken public instances had been removed.
