### ISSUE TITLE
All Instances running 2.4.7.0 broken?

### ISSUE THREAD

**Issue by TrashAccount3424** [pablouser1/ProxiTok#132]
It seems like all instanced that just updated to 2.4.7.0 do not work anymore.

```
Frontend version: 2.4.7.0
Scraper version: 2.3.6.0
```
```
There was an error processing your request!

HTTP Code: 403

API error code 0 (OK)
```

The instances on 2.4.6.0 still work.
```
Frontend version: 2.4.6.0
Scraper version: 2.3.4.1
```

**Comment by pablouser1** [comment]
The weird thing is, 2.4.7.0 doesn't change how the requests are made. It just takes some additional values from SIGI_STATE. I'm investigating the issue.

**Comment by TrashAccount3424** [comment]
The instance proxitok.privacy.com.de 2.4.7.0/2.3.6.0 Came back to life partially meaning that https://proxitok.privacy.com.de/@willsmith loads but video pages do not like https://proxitok.privacy.com.de/@willsmith/video/7202406586424298795

So maybe it was just coincidental that tiktok blocked/limited these instances at the same time.

Could the video page not working be related to the change in templates/views/video.latte ?

**Comment by cron410** [comment]
Seems to be working on that instance.

**Comment by TrashAccount3424** [comment]
> Seems to be working on that instance.

Agree, must have been an unrelated problem to the last update.
I close this now.
