### ISSUE TITLE
2.4.7.0 instances display HTTP Code: 403 when browsing users under "Discover"

### ISSUE THREAD

**Issue by delendum** [pablouser1/ProxiTok#133]
All 2.4.7.0 instances are having the following problems:

- HTTP Code: 403 received when clicking on any user under "Discover"
- "No video with supported format and MIME type found" when trying to play any video under "Trending" (This one is not new, but worth a mention)

1. Go to "Discover"
2. Click on "Go" for any username
3. See error

I can reproduce this problem on the following instances:
https://proxitok.pufe.org/
https://proxitok.pabloferreiro.es/
https://proxitok.esmailelbob.xyz/
https://tok.artemislena.eu/
https://tok.adminforge.de/
https://proxitok.lunar.icu/
https://tok.thekitty.zone/

https://proxitok.privacy.com.de/ is the only 2.4.7.0 instance I could find that does not exhibit this problem, not sure what they're doing different.

**Comment by shruuub** [comment]
https://tok.habedieeh.re has been updated and now has the same issue. Might revert it for the time being.

**Comment by Alfenstein8** [comment]
https://proxitok.privacy.com.de/ has the same problem now

**Comment by samip5** [comment]
Funny, how my 2.4.6 instance doesn't have that issue... :D
