### ISSUE TITLE
Handle redirect URLS

### ISSUE THREAD

**Issue by bersLucas** [pablouser1/ProxiTok#139]
**Describe the solution you'd like**
Inputting the url https://www.tiktok.com/t/ZTRvGPGkr/ gives the error  **HTTP Code: 400 - Invalid TikTok URL**, because it's the shortened link URL. It should parse the URL and bring up the video for https://www.tiktok.com/@tldv.io/video/7215650522081021189?_t=8b1xyhy5TjS instead of the error.

**Describe alternatives you've considered**
Opening the link in browser and copying the full URL to ProxiTok

**Comment by NoPlagiarism** [comment]
ProxiTok supports shortened links, but not if it starts with `https://www` (Gonna fix). Try removing `https://`, and use [LibRedirect](https://github.com/libredirect/libredirect)
