### ISSUE TITLE
Handling banned users rather than 404

### ISSUE THREAD

**Issue by samip5** [pablouser1/ProxiTok#141]
**Describe the bug**
I'm not sure if this is a bug in reality but it seems that PrixiTok intercepts banned accounts as not found while TikTok app shows then just banned.

**To Reproduce**
1. Searh for britney_mcleann on any PrixiTok instance
2. See it return 404

**Expected behavior**

I have have expected it to show something else than 404 when TikTok says banned on https://www.tiktok.com/@britney_mcleann.

**Enviroment:**

- Deployment method: Kubernetes
- Frontend version: 2.4.9.0
- Scrapper version: 2.3.6.2
- PHP Version: 8.0

**Comment by pablouser1** [comment]
Hi! Thanks to pablouser1/TikScraperPHP@99c75fc1786c63276592b0f9859a232f17876f6a now ProxiTok can detect those different states, now it returns this:
![ban](https://user-images.githubusercontent.com/17802865/229539709-b342d107-c8e3-4d63-8861-49ab8e9985dc.png)

Please confirm that it also works correctly for you.

**Comment by samip5** [comment]
> Please confirm that it also works correctly for you.

Yes, it does now. :)
