### ISSUE TITLE
[INSTANCES] New public instance

### ISSUE THREAD

**Issue by xbdmHQ** [pablouser1/ProxiTok#144]
- URL: https://cringe.xbdm.fun
- Cloudflare: Yes
- Country:  Germany

**Comment by NoPlagiarism** [comment]
Is this instance runs with changed source code or sth?

**Comment by xbdmHQ** [comment]
> Is this instance runs with changed source code or sth?

yeah a bit edited yeah

**Comment by NoPlagiarism** [comment]
> Is this instance runs with changed source code or sth?

So is it or not?

**Comment by xbdmHQ** [comment]
> > Is this instance runs with changed source code or sth?
> 
> So is it or not?

no

**Comment by pablouser1** [comment]
Added to the list of public instances!
