### ISSUE TITLE
Option to download all videos?

### ISSUE THREAD

**Issue by korewatori** [pablouser1/ProxiTok#15]
This probably isn't feasible, but how easy would it be to implement a way of downloading all videos on a page at once? Would help with archiving too

**Comment by pablouser1** [comment]
It is technically possible, but TikTok would probably rate limit the ip making the requests, depending on the amount of videos downloaded of course. I will still try to implement this with the new wrapper being developed on the new-api branch

**Comment by desbest** [comment]
It's better to use a web browser extension to do so. Here's what I use.

- [Video Downloader Helper](https://www.downloadhelper.net/)
- [Bulk Media Downloader](https://add0n.com/media-tools.html)
- [HLS Downloader](https://mybrowseraddon.com/hls-downloader.html)
- [Video Downloader Prime](https://mybrowseraddon.com/download-helper.html)
- [Video and Audio Downloader](https://mybrowseraddon.com/video-audio-downloader.html)

**Comment by RiversideHollow** [comment]
A “profile downloading” option would be a very helpful idea. Even if it have to be on our own instances. So far no online service provides that. And would be really a great help for people with no PC.

Also, if it's possible to add a RSS for the whole profile. Or atleast a txt file, containing the video ids and info.

Thank you.

**Comment by pablouser1** [comment]
I'll close this issue. I'm not planning to implement a mass downloader, mainly because of the rate limit problem. You can still use any of the programs @desbest recommended or use [tiktok-scraper](https://github.com/drawrowfly/tiktok-scraper), which also works nicely.
