### ISSUE TITLE
Remove instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by MagicLike** [pablouser1/ProxiTok#150]
Esmail is actively forbidding members or supporters of the LGBTQIA+ community to use their services via a TOS document*.
This is absolutely queerphobic and extremely discriminating. Therefore I ask to remove their instance `proxitok.esmailelbob.xyz` / `proxitok.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion` from the list, to not further support their actions.

*See the commit here: ~~https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a~~ -> https://web.archive.org/web/20230522041632/https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a

**Comment by NoPlagiarism** [comment]
You can still use their services if you are gay. There's no way to detect your sex partner through ProxiTok or anything :D

**Comment by qasourabastm** [comment]
imagine harsing open source developer to do your dirty work

**Comment by qasourabastm** [comment]
> If he'll change code to block LGBTQ+ hashtags.. Then it's totally Red Flag
i don't see any problem here
his platform his rules
LGBTQ is forbidden in his religion and culture
he didn't harass you people like to did

**Comment by NoPlagiarism** [comment]
Update: a lot of services hosted on esmailelbob.xyz is down now

ProxiTok issue by upptime: https://github.com/NoPlagiarism/services-personal-upptime/issues/181

**Comment by NoPlagiarism** [comment]
It's up now
