### ISSUE TITLE
[INSTANCES] New public instance: https://proxitok.sylentpunk.xyz/

### ISSUE THREAD

**Issue by xbdmHQ** [pablouser1/ProxiTok#153]
- URL: https://proxitok.sylentpunk.xyz/
- Cloudflare: No
- Country: Iceland

**Comment by xbdmHQ** [comment]
Instance is down now, rip

**Comment by NoPlagiarism** [comment]
His WikiLess instance Is down too. So let's wait?

**Comment by xbdmHQ** [comment]
> His WikiLess instance Is down too. So let's wait?
> 
> UPD: All of his sites down too

My guess someone DDoSed him or his VPS couldn't handle the traffic. Or he just got tired and stop self-hosting.

**Comment by pablouser1** [comment]
Still not working, I'm guessing is down forever
