### ISSUE TITLE
Collapse Tags on User listing page

### ISSUE THREAD

**Issue by igalic** [pablouser1/ProxiTok#159]
Some tiktok users post their videos with absolutely excessive amounts of tags.
That's very noticeable on their user page.
There's lots of scrolling to go from video to the next.

**Describe the solution you'd like**

It would be nice if Tags would be collapsed in a _view more_ after the first five

**Describe alternatives you've considered**

i really don't know if there's a better way to do this. my UI skills are nonexistent.

**Comment by pablouser1** [comment]
Yeah, that's really annoying. I've added a collapsible to the tags list (200a6fc1f8ed6a871b505c16a1d5d0e8ae6d7251) to make the UI experience more enjoyable
