### ISSUE TITLE
Unsupported config option for services.signer: 'init'

### ISSUE THREAD

**Issue by codedipper** [pablouser1/ProxiTok#163]
Before submitting an issue, please make sure you are using the latest version of ProxiTok.

**Describe the bug**
The docker-compose fails to start.

**To Reproduce**
`git clone https://github.com/pablouser1/ProxiTok`
`APP_URL='https://proxitok.revvy.de' docker-compose up`

**Expected behavior**
It's supposed to work.

**Logs**
```sh
$ APP_URL='https://proxitok.revvy.de' docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.signer: 'init'
```

**Enviroment (please complete the following information):**
On latest git version `9d9207b05e87b67d6255ca897771da34a7053f20`.
`Docker version 20.10.5+dfsg1, build 55c4c88`
`docker-compose version 1.25.0, build unknown`

- Deployment method (if possible): docker
- Frontend version: `sha256:0a775a0933f86d83614e33e20995b4f3c75483e11a2fe466ac0d45ab80ead061`
- Scrapper version: N/A
- PHP Version: `trafex/php-nginx:3.1.0` (PHP 8.1)

You can find the frontend and scrapper version on /about

**Comment by pablouser1** [comment]
Uuuuugh... This should have been fixed with the custom php config file but for some reason is not working. This error happens because PHP doesn't get the env variables provided on `docker-compose.yml`. I'm working on it.

**Comment by pablouser1** [comment]
Hi, Docker Compose v1 is no longer receiving updated and the `init` config option is only available on version 2 or up.

You can:
* Upgrade Docker Compose to version 2
* Remove the init key (this will make the signer shutdown _slowly_ (0.2 seconds with init, 10 seconds without it)
