### ISSUE TITLE
Unable to play videos starting from any 2nd page

### ISSUE THREAD

**Issue by artemis-faulk** [pablouser1/ProxiTok#165]
(For the moment, all the instances that I've tried have this issue) ;
The fact that, when scrolling through the proxied videos (whether on someone's profile, or scrolling through the videos of a particular tag in general), when I click to play videos featured on the first page, they all work. However, as soon as I click to go to the next page (or any other page after that), and I try to play these videos, none of them play (when I click to play they all get the loading symbol for a few seconds, then the play button greys out, and nothing happens). Thus, only the videos on page 1 work. What may be happening?
Many thanks and have a nice day!

**Comment by cunlem** [comment]
Yes unfortunately this problem has never been fixed. I'm not sure exactly why but it's been like that for a long time.

See #109
