### ISSUE TITLE
Support for urls with user id

### ISSUE THREAD

**Issue by oifj34f34f** [pablouser1/ProxiTok#168]
**To Reproduce**

1. Go to https://www.tiktok.com/@169659436251267072 ("normal" link is https://www.tiktok.com/@dicquewuopamela)
2. Ok
3. Then go to https://proxitok.pabloferreiro.es/@169659436251267072
4. See blank screen

If I'm not mistaken, these types of URLs will help you find the account even if the user has changed his username

**Comment by pablouser1** [comment]
Hi, I didn't know that was possible! The scraper assumed that you would only use usernames so it would crash later on (that's why you got that blank screen). pablouser1/TikScraperPHP@eb12cc62176a58f1952983c34275453c8a4bcc46 fixes this.

Please confirm that it also works on your side
