### ISSUE TITLE
[INSTANCES] New public instance https://cringe.datura.network

### ISSUE THREAD

**Issue by nihilist001** [pablouser1/ProxiTok#169]
- URL: https://cringe.datura.network
- Cloudflare: No, never
- Country: Germany

**Comment by pablouser1** [comment]
Hi, I'm trying to connect to your instance but I'm having an SSL error (PR_END_OF_FILE_ERROR)

**Comment by nihilist001** [comment]
Hello, i'm guessing it should've been temporary, my instance should work now (tested from both my pc and phone)
https://cringe.datura.network/trending

**Comment by pablouser1** [comment]
Ok, now everything is working. Thanks for hosting it! I'm adding it to the list
