### ISSUE TITLE
Redirect with Redirector as well

### ISSUE THREAD

**Issue by Cade66** [pablouser1/ProxiTok#17]
ProxiTok works nicely, thanks.

README.md states "_If you want to automatically redirect Tiktok links to ProxiTok, download Libredirect_"
**_Libredirect_** is a great extension but you may as well redirect Tiktok links to ProxiTok with the **_Redirector_** extension (Firefox, not sure for other browsers) :

```
Description: TIKTOK TO PROXITOK
Example URL: https://www.tiktok.com/@valerisssh
Include pattern: (.*//.*)(tiktok.com)(.*)
Redirect to: https://proxitok.herokuapp.com$3
Example result: https://proxitok.herokuapp.com/@valerisssh
Pattern type: Regular Expression
Apply to: Main window (address bar)
```
Whatever redirect tool, ProxiTok is top :=)

**Comment by pablouser1** [comment]
Added with 1eb66261531a2d7977238684937824716cfa74c8
