### ISSUE TITLE
Proxitok cant search by some tags

### ISSUE THREAD

**Issue by ggaast** [pablouser1/ProxiTok#176]
In main menu, when trying to search by tag, it loads the page, but it says `No items sent by TikTok!`

**To Reproduce**
1. Go to Proxitok instance
2. Select `Tag` from drop-down menu
3. Enter random tag name
4. See this page with error

**Expected behavior**
Should be loading fine.

**Enviroment:**
Its the same in every instance.

Not sure, you can do much about that. it seems, like tiktok is somehow preventing you from getting this info, I idk, may be not

![image](https://github.com/pablouser1/ProxiTok/assets/92104930/ea4554a8-3a00-4415-b96b-43b2ce3be20e)

**Comment by pablouser1** [comment]
Maybe related to #179? I've been searching tags using some public instances and it did show items. Please confirm if it's also fixed on your side

**Comment by ggaast** [comment]
![image](https://github.com/pablouser1/ProxiTok/assets/92104930/9a88a2e7-5cc7-4a5c-8afb-aa673d6e1b27)
Now its:

**Comment by ggaast** [comment]
Try tag `fpv`

**Comment by pablouser1** [comment]
Hi, using ProxiTok version 2.4.9.3 and scraper version 2.4.0.2 I can get the results like this:
![Screenshot 2023-10-05 at 20-01-29 #fpv TikTok](https://github.com/pablouser1/ProxiTok/assets/17802865/93d7a5ed-06c8-4121-9399-d67f18be26dc)

Is the instance you are using running an old version of ProxiTok?

**Comment by ggaast** [comment]
Welp, right, Its working on `2.4.9.3` + `2.4.0.2`. Thank you!
