### ISSUE TITLE
[INSTANCES] New public instance: tt.opnxng.com

### ISSUE THREAD

**Issue by extremelyonline** [pablouser1/ProxiTok#182]
- URL: https://tt.opnxng.com
- Cloudflare: No
- Country: Singapore 🇸🇬 

- hosted by about.opnxng.com
- Thank you!

**Comment by tinfoil-hat-net** [comment]
I as well created a new instance:

- URL: proxitok.tinfoil-hat.net
- Country: Germany :de: 
- hosted by me: tinfoil-hat.net

     - cheers

**Comment by pablouser1** [comment]
Hello! Thanks for hostin a public instance. I have added it to the list.
