### ISSUE TITLE
Not a valid URL error

### ISSUE THREAD

**Issue by proof-llc** [pablouser1/ProxiTok#184]
**Describe the bug**
Preview and download with watermark gives me error: Not a valid URL. Download without watermark works.

**Logs**
No errors in any of the 3 docker instances. 

**Enviroment (please complete the following information):**
running latest docker compose

Frontend version: 2.4.9.3
Scraper version: 2.4.0.2

**Comment by pablouser1** [comment]
Fixed with #224 and 9ac169d480ce6a4c879465156cd58acbd4277a8e
