### ISSUE TITLE
Support full TikTok URL paths

### ISSUE THREAD

**Issue by torresjrjr** [pablouser1/ProxiTok#19]
Currently, a full proper TikTok link looks like this:

  https://www.tiktok.com/@papidog01/video/7025547126109261061

However, ProxiTok provides a view for only this URL pattern:

  https://proxitok.herokuapp.com/video/7025547126109261061

One can't simply substitute the domain part. It is required that one tediously removes the <@username> section of the URL. Of course, a browser plugin like LibRedirect can do this step for you, but this needlessly complicates and bloats other software.

I am the maintainer of linkchanbot, a Telegram bot which functions similarly to LibRedirect.

  https://sr.ht/~torresjrjr/linkchanbot/

It currently does not have the ability to manipulate link URL paths, and will not for the forseeable future. linkchanbot is meant to be simple. It would be much easier if ProxiTok simply supported the full URL pattern from TikTok.

How feasible is this? Thank you for your time.

**Comment by pablouser1** [comment]
Fixed with 6eee156541a0b127caaeff293ea3c50cb043f88d. Now Proxitok allows both /video/ID and /@USERNAME/video/ID
