### ISSUE TITLE
For banned/deleted users and vids use tiktok archivers like tik.fail

### ISSUE THREAD

**Issue by leleleSDX** [pablouser1/ProxiTok#193]
So Proxitok works great and all. But what about when vids are banned or taken down. It just spits out an error. There are a couple of tiktok archivers out there. The one I've been using is tik.fail. They even archive captions and metadata. So is there anyway to make a proxitok instance use a local archive that's been downloaded using tik.fail. I believe they are their own API that they use. Make the two APIs talk to each other. 

![tikfail](https://github.com/pablouser1/ProxiTok/assets/6260996/8d1d5141-5895-49f0-8acd-4d8589fe8079)

My idea is:

1.  You want a user to be archived localy. It doesn't matter if they're banned or not.
2. Use tik.fail's API to download it for you with all the important metadata.
3. Modify Proxitok to use your local database.
4. You now have an offline viewer for tiktoks.

**Comment by Jji666** [comment]
Doesnt work

**Comment by pablouser1** [comment]
The website looks inactive, closing the issue for now.

**Comment by BizarreWilliam** [comment]
Long ago this has ended, rip
