### ISSUE TITLE
Only older posts are retrieved

### ISSUE THREAD

**Issue by telmer-adomix** [pablouser1/ProxiTok#195]
**Describe the bug**
While using the official instance, for several days now, in several user profiles only older posts are available. According to my knowledge of affected profiles, the number of lost posts appears to be variable without obvious reasons.

For example:
https://proxitok.pabloferreiro.es/@avvocatodellatomo (first post visible is from July 4, 2023; I think a dozen or so recent posts are missing)
https://proxitok.pabloferreiro.es/@ottolinatv (first post visible is from March 5, 2022; this profile has been updating almost daily in recent months, so hundreds of posts may be missing)
https://proxitok.pabloferreiro.es/@michaelbuble (first post visible is from November 12, 2023; it may well be the last post)

I'm using Firefox as a browser, most recent version.
Unfortunately, I can't find cookies or cache data to clear regarding proxitok.pabloferreiro.es as a website (and can't currently clear everything), so I'm not sure whether it's my system's fault. Does anyone experience the same?

**Comment by vengefulpunk** [comment]
ProxiTok displays the pinned posts first. After the pinned posts(ottolinatv & avvocatodellatomo both have three pinned posts) it is showing me a post from today except for [michaelbuble who does not have any pinned posts but his most recent is from November 12th.

**Comment by telmer-adomix** [comment]
Thank you for answering. My mistake, I wasn't expecting it: either both of them pinned several old posts recently or ProxiTok ignored this settings in the past (I haven't been using it in the last few months). I'll close this issue.
