### ISSUE TITLE
Videos don't load in Safari in either iOS or macOS

### ISSUE THREAD

**Issue by semicolonsnet** [pablouser1/ProxiTok#20]
For all videos, I get the video not available symbol and an error when attempting to play. Error shown in Web inspector:

Unhandled Promise Rejection: NotSupportedError: The operation is not supported.

**Comment by ryb** [comment]
I think this is because the server isn't setting the right content type in the headers.

**Comment by pablouser1** [comment]
> I think this is because the server isn't setting the right content type in the headers.

Thanks for pointing it out. It has been patch with this commit: 9a35c6102346f15f57400e05e5aca5275afd2756
Now all videos return 'video/mp4'
Hopefully this fixes the issue

**Comment by soujdfig** [comment]
Videos won't play on my instance. Everything else seems to work.

**Comment by pablouser1** [comment]
@semicolonsnet it should work now, please check it with your device and close this issue if it works
