### ISSUE TITLE
[INSTANCES] New public instance

### ISSUE THREAD

**Issue by drizzt** [pablouser1/ProxiTok#200]
- URL: https://proxitok.belloworld.it
- Cloudflare: No
- Country: Germany

This instance includes https://github.com/pablouser1/TikScraperPHP/pull/16, so you can use it to get videos :)

**Comment by wedcf120** [comment]
but the user page still not working? like https://proxitok.belloworld.it/@****

**Comment by Nekothegamer** [comment]
yeah user pages are still not working

**Comment by norahqueen** [comment]
thanks @drizzt this got my redirection extension working again! :)

**Comment by pablouser1** [comment]
Thanks for hosting a ProxiTok instance! I have added it to the list.

PD: That pull request has recently been merged, thanks for the trouble of adding it yourself
