### ISSUE TITLE
[INSTANCES] New public instance

### ISSUE THREAD

**Issue by nyuuzyou** [pablouser1/ProxiTok#202]
- URL: https://proxitok.ducks.party
- Cloudflare: No
- Country: Netherlands

**Comment by nyuuzyou** [comment]
I am going to temporarily disable the instance to conserve server resources due to issues with Proxitok caused by updates to the API. Please tag me when the issues are fixed/fork appears.

**Comment by NoPlagiarism** [comment]
https://github.com/pablouser1/TikScraperPHP/pull/16
