### ISSUE TITLE
[INSTANCES] Offline instances

### ISSUE THREAD

**Issue by NoPlagiarism** [pablouser1/ProxiTok#207]
- proxitok.kyun.li
    - AFAIK, down from 4th of November 2023 (https://github.com/NoPlagiarism/services-personal-upptime/issues/3028)
- ~~proxitok.esmailelbob.xyz~~
    - ~~AFAIK, down from 10th of November 2023~~ (https://github.com/NoPlagiarism/services-personal-upptime/issues/3222)
    - It's up now

**Comment by NoPlagiarism** [comment]
will close #150 due technical reasons

**Comment by pablouser1** [comment]
Ok, will remove it. Also, proxitok.esmailelbob.xyz looks like is also down?

Entering `esmailelbob.xyz` redirects you to a rick-roll so :shrug:

**Comment by NoPlagiarism** [comment]
My Upptime repo is kinda abandoned for now, so can't tell when it fell down.
All of  Esmail EL BoB instances are down now. I'll notify if his ProxiTok instance will be up again
