### ISSUE TITLE
Significance of specifying cloudflare?

### ISSUE THREAD

**Issue by GlytchMeister** [pablouser1/ProxiTok#218]
In the public instances page, there's a column specifying if the instance uses cloudflare.  What is the significance of this?

I suppose it would be nice to have this explained on the public instances page.

(I chose not to list this as an enhancement because this isn't a feature request for proxitok itself)

Thanks

**Comment by Wave6677** [comment]
CF is listed as if a user is using ProxiTok to circumvent censorship or simply doesn't want to be tracked by a big tech company. CF adds a Proxy that they can unencrypt the HTTPS data being sent by you and see exactly what youre doing on the page. Its convenient for some people as CF can mirror your page on their servers around the world, but at the same time you are trusting one of the largest tech organizations not to sell you out to a company or government.

**Comment by NoPlagiarism** [comment]
For more info read: https://notabug.org/dCF/deCloudflare
