### ISSUE TITLE
tiktok sucks

### ISSUE THREAD

**Issue by lentas1** [pablouser1/ProxiTok#219]
https://lentas1.github.io/tiktoksucks/

**Comment by NoPlagiarism** [comment]
What the fuck, we know already, Stop Spamming
I see you already done this here: https://github.com/zyronon/douyin/issues/91

- First of all, this project and douyin are not endorsed or affiliated with TikTok. It's not TikTok mods you install or sth like that
- You really nailed the job with writing simple HTML file with lossiest png
- This subreddit is banned already
- Stop Spamming
