### ISSUE TITLE
Feature request: copy video URLs with JS disabled?

### ISSUE THREAD

**Issue by KanadeTachibana2** [pablouser1/ProxiTok#22]
hello, I'm aware that making the frontend compatible with JS disabled is in the TODO list.

but, in the meantime, would it be feasible to allow us to copy the TikTok video URLs with JS disabled? so we can play them in an external video player (with yt-dlp).

also, right now, those URLs are missing the `www.` prefix, which prevents them from being played with yt-dlp. (you have to manually add the `www.` before `tiktok.com` to make it work; otherwise, yt-dlp thinks it's an invalid url)

**Comment by pablouser1** [comment]
Hello, this was fixed with this commit: 44ee065ec6f224326d490a3a8ef2eb9b32ce23b8
Now the whole website works without JS.

**Comment by KanadeTachibana2** [comment]
that's sick! thank you so much!
