### ISSUE TITLE
Search button isn't working?

### ISSUE THREAD

**Issue by PrincessMiki** [pablouser1/ProxiTok#23]
Searching for both users and tags aren't working

**Comment by pablouser1** [comment]
Not working exactly how? You get a 403 error or a VERIFY_CODE? Maybe has something to do with #25?

**Comment by Wonderwize** [comment]
All Japanese tags give search errors. For example:

proxitok.herokuapp.com/tag/名言
Gives an error with HTTP Code: 400

tiktok.com/tag/名言
Gives plenty of results.
