### ISSUE TITLE
Undefined constant TikScraper\Common::DEFAULT_USERAGENT

### ISSUE THREAD

**Issue by TheFrenchGhosty** [pablouser1/ProxiTok#26]
Follow up to https://github.com/PussTheCat-org/docker-proxitok-quay/issues/3

Every single page trigger this error, making ProxiTok completely unusable.

This seem to be related to a recent change to the docker image `zenika/alpine-chrome`.

`
Fatal error: Uncaught Error: Undefined constant TikScraper\Common::DEFAULT_USERAGENT in /var/www/html/vendor/pablouser1/tikscraper/src/Helpers/Signer.php:58 Stack trace: #0 /var/www/html/vendor/pablouser1/tikscraper/src/Helpers/Signer.php(35): TikScraper\Helpers\Signer->setupSelenium('http://proxitok...') #1 /var/www/html/vendor/pablouser1/tikscraper/src/Sender.php(37): TikScraper\Helpers\Signer->__construct(Array) #2 /var/www/html/vendor/pablouser1/tikscraper/src/Api.php(17): TikScraper\Sender->__construct(Array) #3 /var/www/html/app/Helpers/Wrappers.php(88): TikScraper\Api->__construct(Array, Object(App\Cache\RedisCache)) #4 /var/www/html/app/Controllers/UserController.php(14): App\Helpers\Wrappers::api() #5 [internal function]: App\Controllers\UserController::get('memes') #6 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(476): forward_static_call_array(Array, Array) #7 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\Router\Router->invoke('UserController@...', Array) #8 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle(Array, true) #9 /var/www/html/index.php(14): Bramus\Router\Router->run() #10 {main} thrown in /var/www/html/vendor/pablouser1/tikscraper/src/Helpers/Signer.php on line 58
`

Using my docker image: https://github.com/PussTheCat-org/docker-proxitok-quay

**Comment by pablouser1** [comment]
Fixed with 2c68b34d063fd6d9be4340e008b8ae8c1ab98923

**Comment by TheFrenchGhosty** [comment]
@pablouser1 It doesn't error out instantly now, but trending/discover hangs until it shows this error, profiles load SLOWLY:

`
Fatal error: Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"excludeSwitches":["enable-automation"],"useAutomationExtension":false,"args":["--headless","--disable-gpu","--no-sandbox","--disable-blink-features=AutomationControlled","--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY","goog:chromeOptions":{"excludeSwitches":["enable-automation"],"useAutomationExtension":false,"args":["--headless","--disable-gpu","--no-sandbox","--disable-blink-features=AutomationControlled","--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36"]}}} Operation timed out after 30000 milliseconds with 0 bytes received in /var/www/html/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:333 Stack trace: #0 /var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(131): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand)) #1 /var/www/html/vendor/pablouser1/tikscraper/src/Helpers/Signer.php(66): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://proxitok...', Object(Facebook\WebDriver\Remote\DesiredCapabilities)) #2 /var/www/html/vendor/pablouser1/tikscraper/src/Helpers/Signer.php(35): TikScraper\Helpers\Signer->setupSelenium('http://proxitok...') #3 /var/www/html/vendor/pablouser1/tikscraper/src/Sender.php(37): TikScraper\Helpers\Signer->__construct(Array) #4 /var/www/html/vendor/pablouser1/tikscraper/src/Api.php(17): TikScraper\Sender->__construct(Array) #5 /var/www/html/app/Helpers/Wrappers.php(88): TikScraper\Api->__construct(Array, Object(App\Cache\RedisCache)) #6 /var/www/html/app/Controllers/TrendingController.php(12): App\Helpers\Wrappers::api() #7 [internal function]: App\Controllers\TrendingController::get() #8 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(476): forward_static_call_array(Array, Array) #9 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\Router\Router->invoke('TrendingControl...', Array) #10 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle(Array, true) #11 /var/www/html/index.php(14): Bramus\Router\Router->run() #12 {main} thrown in /var/www/html/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php on line 333
`

The chrome container is reporting:

`
[1649771217.113][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
`

PS: this is all my instance if you want to test: https://proxitok.pussthecat.org/

**Comment by pablouser1** [comment]
> Operation timed out after 30000 milliseconds with 0 bytes received

That looks like a timeout error, PHP isn't receiving anything from the chromedriver server

> Fatal error: Uncaught TypeError: TikScraper\Models\Feed::setNav(): Argument #3 ($maxCursor) must be of type string, null given

Maybe has something to do with #21, TikTok returned a structure that was not expected and it crashed, maybe now it works?
I've been using your Docker image and I had good results

**Comment by TheFrenchGhosty** [comment]
>That looks like a timeout error, PHP isn't receiving anything from the chromedriver server

Yeah, I think I got this because ProxiTok started faster than the chromedriver.

I guess we can consider this issue solved.

**Comment by pablouser1** [comment]
> other than [1649771217.113][WARNING]: Deprecated chrome option is ignored: useAutomationExtension

Fixed with e545bd6ddd74696ccea16c49b899d215c6d755cd
