### ISSUE TITLE
Typed property TikScraper\Models\Info::$detail must not be accessed before initialization

### ISSUE THREAD

**Issue by TheFrenchGhosty** [pablouser1/ProxiTok#28]
All profile pages don't load (pick any https://proxitok.pussthecat.org/discover ):

`
Fatal error: Uncaught Error: Typed property TikScraper\Models\Info::$detail must not be accessed before initialization in /var/www/html/vendor/pablouser1/tikscraper/src/Api.php:70 Stack trace: #0 /var/www/html/app/Controllers/UserController.php(15): TikScraper\Api->getUserFeed('billieeilish', 0) #1 [internal function]: App\Controllers\UserController::get('billieeilish') #2 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(476): forward_static_call_array(Array, Array) #3 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\Router\Router->invoke('UserController@...', Array) #4 /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle(Array, true) #5 /var/www/html/index.php(14): Bramus\Router\Router->run() #6 {main} thrown in /var/www/html/vendor/pablouser1/tikscraper/src/Api.php on line 70
`

**Comment by pablouser1** [comment]
Thanks for pointing out the issue!

Patched with 47a3dc7e763294eb5d17796d340bce0fec3a4abc
Right now it throws lots of warnings, but that will be also be fixed eventually.

**Comment by TheFrenchGhosty** [comment]
... the warnings are displayed on the web interface (see my instance again), it's not good xD

**Comment by pablouser1** [comment]
Warnings are now hidden for that specific line
