### ISSUE TITLE
Can ProxiTok open share links?

### ISSUE THREAD

**Issue by djl0** [pablouser1/ProxiTok#30]
I often receive links in the form of https://vm.tiktok.com/{share_id} which then re-directs to the usual @author/video_id. Does this app already resolve that redirect, and if not, I'd like to put it on the radar of the team. Thanks

**Comment by pablouser1** [comment]
> Does this app already resolve that redirect

Yes, you can take that share_id and type it on the Video Id form. The backend will do the redirection for you and load the video.
