### ISSUE TITLE
cant see multiple pages

### ISSUE THREAD

**Issue by asdkojsdjmkfmzk** [pablouser1/ProxiTok#31]
EXPLANATION: I search up a tag, user, or whatever, and then when I'm done browsing and get to the bottom and click the "next" button, it keeps saying "no more items sent by TikTok", yet it states there's more under the user/tag

https://user-images.githubusercontent.com/84987355/167754695-d222ede0-ac25-4bcc-8fd2-fc5e9ff58295.mp4

![Screenshot 2022-05-10 19 07 22](https://user-images.githubusercontent.com/84987355/167754718-3ee03e4d-7e4a-4715-9355-0b8d399ae37d.png)

**Comment by pablouser1** [comment]
This is an issue with hashtags on instances running in Legacy mode.
(Maybe) sending both a minCursor and a maxCursor will solve the problem, I'll try to check if this solution works.
In the meantime, you can check [this](https://github.com/pablouser1/ProxiTok/wiki/Public-instances) wiki page for all public instances available. Make sure it does not force legacy mode.

**Comment by pablouser1** [comment]
> Can you elaborate of that min/maxCursors are? I'm a bit confused.

TikTok requieres sending both a minCursor and a maxCursor for navigation purposes, but right now ProxiTok only sends a maxCursor. MinCursor is _always_ set to 0. Maybe that's why it doesn't work.

**Comment by pablouser1** [comment]
This is now been (inderectly) fixed. Now that Legacy mode no longer works, all instances have to run on standard mode. In this mode this issue doesn't happen, so I'll close this now.
