### ISSUE TITLE
Wrong rss feed times.

### ISSUE THREAD

**Issue by glottis0q** [pablouser1/ProxiTok#32]
<img width="182" alt="Screenshot 2022-05-12 at 21 23 59" src="https://user-images.githubusercontent.com/93644977/168152728-bf2165a1-0c41-41e7-a9bc-f32ae1180e0f.png">

I added the rss feed from https://proxitok.herokuapp.com/@oscarstembridge/rss and the times are a little wrong xD

I like ProxiTok. Works great so far. The ability to add it via rss is amazing

**Comment by glottis0q** [comment]
https://github.com/pablouser1/ProxiTok/commit/bd1642957c9f0ccca238f04a8c98dbd6d7cbce9b#diff-ae1982f93ea64e9ac9c22cf6ac3d300445de0b7d87d1555f42e497f001aec7cfR28 might be the line that needs some attention

**Comment by pablouser1** [comment]
Fixed with 9a662ffe1b9f8043ab113e6f28432b06f8bb9d40
