### ISSUE TITLE
Wrong rss item urls

### ISSUE THREAD

**Issue by pabloscloud** [pablouser1/ProxiTok#34]
It’s only the username instead of the whole url.

**Comment by pablouser1** [comment]
Hi, maybe this was related to #56? Can you check if it is now working?

**Comment by pablouser1** [comment]
> This is a separate issue - some rss readers require for the entire urls to be present

That is controlled by the [APP_URL env variable](https://github.com/pablouser1/ProxiTok/wiki/Configuration#app_url=)

Maybe this has something to do with the Docker deployment method.
Right now Docker sets the default url to '/' which does work for HTML, but doesn't for those rss readers.

A workaround for this can be setting a custom env variable before using docker-compose, like:
```bash
APP_URL='https://example.com' docker-compose up
```

If the instance is using the manual deploy method, it should set that env variable on the .env file

**Comment by pablouser1** [comment]
> could you try that on the official instance

The official instance already has the correct APP_URL env, so it should work.

> it would also be great to it add to the wiki

You're right, I'll add a warning for Docker users on the wiki

**Comment by pabloscloud** [comment]
This is not fixed. It’s still not working in the iOS reeder app.

**Comment by pablouser1** [comment]
I think it is now fixed, now the whole url is shown instead of only the path.

@pabloscloud can you confirm it works now on your iOS app?

**Comment by pabloscloud** [comment]
It doesn’t. I’m using Reeder on iOS and macOS and it doesn’t work in NetNewsWire either

**Comment by pablouser1** [comment]
I've forgot to add the APP_URL env variable to the official instance... now it shows the whole url

**Comment by pabloscloud** [comment]
Yes, works now
