### ISSUE TITLE
Optional parameter $config declared before required parameter $legacy

### ISSUE THREAD

**Issue by TheFrenchGhosty** [pablouser1/ProxiTok#38]
`
Deprecated: Optional parameter $config declared before required parameter $legacy is implicitly treated as a required parameter in /var/www/html/vendor/pablouser1/tikscraper/src/Api.php on line 17
`
`
Deprecated: Optional parameter $legacy declared before required parameter $cache is implicitly treated as a required parameter in /var/www/html/vendor/pablouser1/tikscraper/src/Items/Trending.php on line 11
`
`
Deprecated: Optional parameter $legacy declared before required parameter $cache is implicitly treated as a required parameter in /var/www/html/vendor/pablouser1/tikscraper/src/Items/Base.php on line 24
`

**Comment by TheFrenchGhosty** [comment]
@pablouser1 By the way: Can you please seriously test your code before pushing it? Every single time I updated things break.

**Comment by pablouser1** [comment]
> @pablouser1 By the way: Can you please seriously test your code before pushing it? Every single time I update things break. It's getting tiring.

Yeah, I should test stuff using Docker instead of my local installation... Anyways, I'm planning to add PHPUnit to the project to help with that.

**Comment by TheFrenchGhosty** [comment]
>Yeah, I should test stuff using Docker instead of my local installation... Anyways, I'm planning to add PHPUnit to the project to help with that.

Your local installation isn't necessarily running the same version of PHP that the docker image is using. Docker is made to be consistent across installation, so definitely use it to test.
