### ISSUE TITLE
Trending Broken -  "No items sent by TikTok!"

### ISSUE THREAD

**Issue by TheFrenchGhosty** [pablouser1/ProxiTok#39]
If "Forcing Legacy mode" is set to no (the default on https://proxitok.pussthecat.org/ ), the trending page ( https://proxitok.pussthecat.org/trending ) will display "No items sent by TikTok!" even though profiles will load fine.

Setting it to "yes" will make the trending load.

**Comment by pablouser1** [comment]
(indirectly) fixed thanks to 90a2d2ec289c3644802c6595fc242682e2abac52

Make sure to run the latest version of both ProxiTok and SignTok
