### ISSUE TITLE
all public instances on error at search by user

### ISSUE THREAD

**Issue by herokuhint** [pablouser1/ProxiTok#44]
Hi pablo,
all public instances on error at response from search by user (default fields on index page load) , please fix them
thanks

**Comment by pablouser1** [comment]
Most probably those instances were on legacy mode. As far as I'm aware, TikTok has definitely killed their /node (legacy) endpoints, now everyone of those endpoints return a 502 error. I'll wait some time to see if this is only temporary, but it looks like legacy is no longer usable.

**Comment by pablouser1** [comment]
This has now been fixed. Legacy mode has been removed and the official instance has been updated to standard mode. I'll close this issue.
