### ISSUE TITLE
Errors HTTP 50x

### ISSUE THREAD

**Issue by stemy2** [pablouser1/ProxiTok#46]
Hello,

I tried proxitok on the flagship instance and on mine, but all i have is a blank page. According the web inspector, this is an HTTP 500 error in both case. Only the main page and the discover page are working, and the trending page give me a HTTP 502 error.

**Comment by pablouser1** [comment]
Duplicated of #45

> I think that TikTok is starting to enforce more their "bot detection" mecanism on their web. Normally, when you were detected as a bot, you were required to type a captcha. That initial request would throw a 403 code error, which then the program would correctly handle.

> That doesn't happen anymore, now it returns a 200 OK code, which is not expected. That's what's causing those errors. I'm looking for a fix now.

That's why the server returns a 500 error.

I'll close this issue, it will be continued there.
