### ISSUE TITLE
make app.json file for preset env value/s & buildpack/s for deploy on heroku

### ISSUE THREAD

**Issue by elmirarokni** [pablouser1/ProxiTok#48]
Hi pablo,
please make app.json file in root of project for preset env value/s & buildpack/s requirement for deploy on heroku.
for more see here : https://devcenter.heroku.com/articles/app-json-schema
& also put markdown below on README.md file for easily deploy without using heroku cli:
`[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy)`
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy)
waiting for your response
finest regards

**Comment by pablouser1** [comment]
Hi, it has been added with 59029e48ad37fa5586667ade31005e5c0d6e3d13

I've done a test deployment and it works out of the box.

The Deploy button can be found on the Self-Hosting wiki article
