### ISSUE TITLE
Error code 504

### ISSUE THREAD

**Issue by AnonWombat** [pablouser1/ProxiTok#5]
Hey there :)

![Screenshot_20220119-180201_Firefox Nightly](https://user-images.githubusercontent.com/44946401/150232367-20599f5b-6921-4450-886d-2463d472f9e8.png)

I'm getting this warning when I try to view a video.

**Comment by pablouser1** [comment]
Hi, it's already fixed, there was an issue with the curl wrapper for php I was using, I ended uninstalling it and reverting to the old method I was using.
