### ISSUE TITLE
RSS Auto-discovery

### ISSUE THREAD

**Issue by kevincox** [pablouser1/ProxiTok#50]
It would be great to add an auto-discovery `<link>` tag to the pages so that browser extensions auto-discover feeds and users can just paste the URL into their feed readers to subscribe rather than trying to search for the link on the page. For example user profiles should have references to the feed for that profile.

**Comment by pablouser1** [comment]
Hi, thanks for pointing this out, I didn't know this existed. It has been added with 9d37bc433d5308623fdb846913fc2c82e5218f43

**Comment by kevincox** [comment]
Thanks!

**Comment by kevincox** [comment]
It would also be nice to have the user's feed linked from the video page. That way it is easy to subscribe to a user when a video is playing.
