### ISSUE TITLE
Suggestion: Input URL instead of ID

### ISSUE THREAD

**Issue by igalic** [pablouser1/ProxiTok#58]
related to #57 a usability improvement would be to just take a TikTok URL as Input
the parser could be triggered by checking if the string starts with https://

This is especially convenient when using the service from a phone where hopping around in a string and editing it quickly is ***hard***.

**Comment by pablouser1** [comment]
Hey, if I understand correctly, you're asking for a new input field that just takes a TikTok URL, then the server will redirect you to the correct user/tag/...

It looks like a good improvement, specially for phone users, I'll implement it.
