### ISSUE TITLE
Feature Request: RSS

### ISSUE THREAD

**Issue by rozbb** [pablouser1/ProxiTok#6]
Thank you for making this frontend! One thing that would be nice is offering an RSS feed for user pages. That way I can follow creators in a centralized way that syncs with all my devices

For reference, this is already done in Invidious ([example](https://invidious.snopyta.org/feed/channel/UC9RM-iSvTu1uPJb8X5yp3EQ), [source](https://github.com/iv-org/invidious/blob/326a362eb892b1e6a60413b701a61e364f53c485/src/invidious/routes/feeds.cr#L139)) and Bibliogram ([example](https://bibliogram.mrosenberg.pub/u/shidizen/rss.xml), [source](https://github.com/bmrz2019/bibliogram/blob/3700b3a9ac824b501615413c0b2181a099076d09/src/lib/structures/TimelineEntry.js#L294))

**Comment by pablouser1** [comment]
Thanks for the suggestion! I've added RSS with this commit: bd1642957c9f0ccca238f04a8c98dbd6d7cbce9b
For fetching a RSS feed you have to append /rss to the url (Example: if you want to get a feed of the user "example" you would have to use this url: https://proxitok.herokuapp.com/@example/rss)
It supports users, tags, and trending.

**Comment by rozbb** [comment]
Amazing, and so fast too! I left 1 comment on the commit, noting that the RSS links should be HTTPS, but otherwise this is great.
