### ISSUE TITLE
User posts are not retreived anymore

### ISSUE THREAD

**Issue by vdemay** [pablouser1/ProxiTok#60]
Getting posts from user fails: e,g, https://proxitok.herokuapp.com/@willsmith
I suppose something change on tiktok side

**Comment by pablouser1** [comment]
Hi, indeed something changed on their servers, I'm investigating it now. Maybe it has to do with the X-Bogus and msToken GET params? I'm working on a way to generate those tokens.

**Comment by eUgEntOptIc44** [comment]
@pablouser1 would be very grateful for a short update on this as I still experience the error mentioned in #61.

**Comment by pablouser1** [comment]
> would be very grateful for a short update on this

The "main" fix being discussed right now is in https://github.com/davidteather/TikTok-Api/issues/906#issuecomment-1194750614 but it involves logging into a TikTok account, which (at least in my opinion) defeats the purpose of using an alternative frontend.

As I said before, I ended up generating X-Bogus and msToken tokens but even with those I'm still getting captcha issues. Maybe they are not valid?

**Comment by pablouser1** [comment]
This issue has been fixed :tada:

Thanks to @H1W0XXX we can now generate valid X-Bogus tokens.

This, indirectly, fixes #39 and breaks Discover.

For instance hosters: Make sure to use the latest version of ProxiTok and SignTok. For now, only SignTok supports X-Bogus, but eventally other signers will support it.

**Comment by desbest** [comment]
> This issue has been fixed 🎉
> 
> For instance hosters: Make sure to use the latest version of ProxiTok and SignTok. For now, only SignTok supports X-Bogus, but eventally other signers will support it.

If the issue is fixed, when will the official `proxitok.herokuapp.com` instance be updated to the latest version, to reflect the changes?

**Comment by NoPlagiarism** [comment]
@desbest Instance updated
[Check url mentioned earlier](https://proxitok.herokuapp.com/@willsmith)

**Comment by desbest** [comment]
Why does this profile not work?
[Check this URL for details.](https://proxitok.herokuapp.com/@avamax)

> There was an error processing your request!
> HTTP Code: 200
> API error code -1 (UNKNOWN_ERROR)

**Comment by NoPlagiarism** [comment]
or is it?
Checked 5 minutes ago
![png](https://i.vgy.me/eeGWTt.png "Checked 5 mins ago")

**Comment by pablouser1** [comment]
I'm currently not having issues on the official instance. I'll leave this issue opened for some time in case something happens.

**Comment by NoPlagiarism** [comment]
@pablouser1 Happened
Problem on ProxiTok 2.4.0.0 or Scraper 2.2.0.0
https://cringe.whatever.social is working

**Comment by pablouser1** [comment]
> @pablouser1 Happened Problem on ProxiTok 2.4.0.0 or Scraper 2.2.0.0 https://cringe.whatever.social is working

https://github.com/pablouser1/ProxiTok/issues/72#issuecomment-1217969598

**Comment by FillingTheVoidOnYT** [comment]
when using the mobile browser duckduckgo no user posts want to load

**Comment by NoPlagiarism** [comment]
> the mobile browser duckduckgo no user pos
instance. Name the instance url

**Comment by FillingTheVoidOnYT** [comment]
> the mobile browser duckduckgo no user pos
> instance. Name the instance url

It’s the official instance

**Comment by pablouser1** [comment]
It looks like it is now stable... I'll close this issue for now
