### ISSUE TITLE
add my site

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [pablouser1/ProxiTok#64]
https://proxitok.esmailelbob.xyz/ and it's tor version http://proxitok.lqs5fjmajyp7rvp4qvyubwofzi6d4imua7vs237rkc4m5qogitqwrgyd.onion

**Comment by NoPlagiarism** [comment]
I thought it be good to wait for fix. Cuz pablouser1 can't check works it or not
But at least, It worked for me before #60

**Comment by pablouser1** [comment]
Hi, thanks for hosting a public instance! It has now been added to the public instances list.

> I thought it be good to wait for fix. Cuz pablouser1 can't check works it or not

I checked if the other features (tag, music, video...) worked, which they do, so I'm including it.

**Comment by EsmailELBoBDev2** [comment]
Hi, @pablouser1 sorry to bother, can you update my onion link to 
http://proxitok.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion/

**Comment by pablouser1** [comment]
> Hi, @pablouser1 sorry to bother, can you update my onion link to http://proxitok.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion/

Updated
