### ISSUE TITLE
Remove proxitok.privacydev.net

### ISSUE THREAD

**Issue by PrivacyDevel** [pablouser1/ProxiTok#65]
I just wanted to let you know that I stopped hosting my ProxiTok instance for now. All requests to this instance will now automatically be redirected to their corresponding tiktok.com URLs, to make the transition as smooth as possible for all current users.

The primary reasons why I stopped hosting my ProxiTok instance are as follows:
1. ProxiTok's feeds have broken for a while now
2. I discovered that you can actually watch TikTok videos using Tor as long as you use a specific enough URL
3. Reading comments is not supported on ProxiTok
4. To download TikTok videos, you can just use yt-dlp

I wish you the best of success with your project going forward!

**Comment by KaKi87** [comment]
Hello,
> I thought you needed a TikTok account to see the comments, but it looks like you can bypass that restriction. [...] for now that's not on my priority list. But it will still be nice to include this feature in the future.

Is that feature request tracked ? Thanks
