### ISSUE TITLE
Update Dockerfile and add whatever.social instance

### ISSUE THREAD

**Issue by privacytime101** [pablouser1/ProxiTok#68]
Hi there, it seems as though the version that pushed Tikscraper to version 2.1.2.0 hasn't been pushed into the Dockerfile yet. 

Additionally, I've begun hosting an instance at https://cringe.whatever.social if it helps. Thank you for this project.

**Comment by pablouser1** [comment]
> Hi there, it seems as though the version that pushed Tikscraper to version 2.1.2.0 hasn't been pushed into the Dockerfile yet.

Looks like there was an issue with PHP's pecl servers that made the builds fail, now they are working.

> Additionally, I've begun hosting an instance at https://cringe.whatever.social/ if it helps. Thank you for this project.

I've been trying to test it, but I'm getting a Bad Gateway error

**Comment by privacytime101** [comment]
That's weird, not sure what happened yet. It's back up, however the scraper version is still on 2.1.1.0 for some reason.

**Comment by pablouser1** [comment]
Thanks for hosting a public instance @privacytime101! I've added it to the list.

> however the scraper version is still on 2.1.1.0 for some reason.

Are you using the manual deploy method? Make sure to run `composer update` after pulling the new version.

**Comment by privacytime101** [comment]
Still the same. Pulled it again and rebuilt it, no update.

**Comment by NoPlagiarism** [comment]
@privacytime101 502 Error again

**Comment by privacytime101** [comment]
@NoPlagiarism Yes, I need to reinstall it because it wasn't working in the first place.

**Comment by privacytime101** [comment]
It's back up, but the API error's still there.

**Comment by pablouser1** [comment]
Hmmm... That's weird... Maybe you are having an issue similar to https://github.com/pablouser1/ProxiTok/issues/72#issuecomment-1222716385

Maybe your IP is already blacklisted by TikTok? @PrivacyDevel fixed it using a proxy to make the request.
