### ISSUE TITLE
new instance

### ISSUE THREAD

**Issue by dhuschde** [pablouser1/ProxiTok#69]
Since there aren't many public Instances rn, i decided to host one.
The Domain would be https://proxitok.dhusch.de
It's hosted in Germany and does not use Cloudflare.

Im using YunoHost to host it btw.

Could you please list this in the public list?

**Comment by NoPlagiarism** [comment]
Please, check if you updated your instance
Your version is lower than actual

**Comment by pablouser1** [comment]
Thanks for hosting a public instance @dhuschde! I'm adding it now, make sure to update it when it is available to you.
