### ISSUE TITLE
Page buttons don't work

### ISSUE THREAD

**Issue by zilpe** [pablouser1/ProxiTok#7]
Hello. The page buttons on your site currently do not work at all:
eg. [https://proxitok.herokuapp.com/@tiktok](https://proxitok.herokuapp.com/@tiktok)

When clicking the next/back buttons, the URL changes but the post contents does not.

Thanks!

**Comment by austinhuang0131** [comment]
Can't seem to reproduce it, maybe you need to enable JavaScript?

**Comment by zilpe** [comment]
Commit 19553f88379ae8b86c90692e8e382870c47bbdcd fixed the issue. Thanks!
