### ISSUE TITLE
Add a 'count' parameter

### ISSUE THREAD

**Issue by k2helix** [pablouser1/ProxiTok#70]
**Is your feature request related to a problem? Please describe.**
Hi, I've been using Proxitok for a while whenever I had to use Tiktok and I'm missing an option to select the number of posts to retrieve from a user, as the limit per page is currently 30.

**Describe the solution you'd like**
It would be nice to be able to specify the number of posts to get, for example with a count parameter in the URL instead/in addition of the cursor parameter. So for example a URL would be like this: 
`https://proxitok.herokuapp.com/@someuser?count=60`

**Comment by NoPlagiarism** [comment]
It's in todo`s... Hah

**Comment by k2helix** [comment]
Ohhh I did not see it! I'm really sorry!
