### ISSUE TITLE
[INSTANCES] New public instance "proxitok.odyssey346.dev"

### ISSUE THREAD

**Issue by Odyssey346** [pablouser1/ProxiTok#75]
- URL: https://proxitok.odyssey346.dev 
- Cloudflare: No
- Country: Poland

**Comment by NoPlagiarism** [comment]
User feed's not working
How did you set up this instance?

**Comment by Odyssey346** [comment]
I used TheFrenchGhosty's Docker image. Should I try the official one? Are there any differences?

**Comment by Odyssey346** [comment]
I also use Caddy for the web server.

**Comment by NoPlagiarism** [comment]
> I used TheFrenchGhosty's Docker image. Should I try the official one? 

You can try

**Comment by Odyssey346** [comment]
Switching to the official one worked. I told TheFrenchGhosty to update his image and he told me that GitHub stopped the CI automatically cause he didn't make a commit in 2 months.

**Comment by pablouser1** [comment]
Hey @Odyssey346, thanks for hosting a public instance! I've added it to the list of public instances.
