### ISSUE TITLE
Video download without watermark is broken

### ISSUE THREAD

**Issue by PrivacyDevel** [pablouser1/ProxiTok#76]
Whenever I try to download a video without the watermark, I get a 147 byte long JSON file instead.
The content looks like this:
`{"log_pb":{"impr_id":"2022082218045401024503224309316C9A"},"status_code":4,"status_msg":"Server is currently unavailable. Please try again later."}`

This happens on all instances as far as I can tell, including the official one.

**Comment by NoPlagiarism** [comment]
LoL.
![image](https://user-images.githubusercontent.com/37241775/186178109-0273cfcb-01ea-4188-ad98-96df2bc3d9bd.png)
Same with tiktokcdn-us.com
Maybe it's TikTok's problem or TikTok's security update
Added those domains to UptimeRobot and waiting for changes

**Comment by NoPlagiarism** [comment]
So... I guess, from now on 
`tiktokcdn.com` and `tiktokcdn-us.com` just  not exists from now on.
Only `p16-sign.tiktokcdn-us.com` and etc

**Comment by NoPlagiarism** [comment]
Problem in TikTokScraper and this url - https://api-h2.tiktokv.com/aweme/v1/play/
You can just open it to be sure

**Comment by NoPlagiarism** [comment]
I've found new solution (without external) by @Sharqo78 
But as he said, it's looking like hell
https://github.com/Sharqo78/VTik/blob/main/src/extractors/extractors.v

**Comment by NoPlagiarism** [comment]
# For anyone who can fix it on PHP in [TikScraperPHP](https://github.com/pablouser1/TikScraperPHP):
User-Agent to use: `Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0`
URL to get data from: `https://api-h2.tiktokv.com/aweme/v1/feed/?aweme_id={str_id}&version_name=26.1.3&version_code=2613&build_number=26.1.3&manifest_version_code=2613&update_version_code=2613&openudid={openudid}&uuid={uuid}&_rticket={seconds}&ts={seconds*1000}&device_brand=Google&device_type=Pixel%204&device_platform=android&resolution=1080*1920&dpi=420&os_version=10&os_api=29&carrier_region=US&sys_region=US%C2%AEion=US&app_name=trill&app_language=en&language=en&timezone_name=America/New_York&timezone_offset=-14400&channel=googleplay&ac=wifi&mcc_mnc=310260&is_my_cn=0&aid=1180&ssmix=a&as=a1qwert123&cp=cbfhckdckkde1`
### About query parameters to insert
- {seconds} - Unix time `time()`
- {seconds*1000) - kinda obvious
- {openudid} - random str 16-len from chars `0123456789abcdef`. I guess `bin2hex(random_bytes(8))` would work
- {uuid} - check {openudid}
- {str_id} - id from full url. Use `Converter->urlToId({url here})` from TikScraper\Helpers

### How to get url
json_result -> `aweme_list -> 0 -> video -> play_addr -> url_list -> 0`
`aweme_list` and `url_list` are lists

**Comment by pablouser1** [comment]
Thanks for the info, both @NoPlagiarism and @Sharqo78!

I've got it working properly with TikScraper, I'm bumping the scraper now.

**Comment by NoPlagiarism** [comment]
@PrivacyDevel Close for now?

**Comment by PrivacyDevel** [comment]
@NoPlagiarism I mean sure. Is it in ProxiTok yet after we upgrade?

**Comment by Sharqo78** [comment]
Well you're welcome guys but the URL isn't from me, I took it from the douyin.wtf project
