### ISSUE TITLE
[INSTANCES] New public instance

### ISSUE THREAD

**Issue by artemislena** [pablouser1/ProxiTok#78]
- URL: https://tok.artemislena.eu (Tor/Onion version at http://tok.lpoaj7z2zkajuhgnlltpeqh3zyq7wk2iyeggqaduhgxhyajtdt2j7wad.onion)
- Cloudflare: No
- Country: Germany

**Comment by pablouser1** [comment]
Thanks for hosting a public instance @artemislena! It has been added to the pubic instances list.
