### ISSUE TITLE
Feature Request: Add Username and video ID in metadata?

### ISSUE THREAD

**Issue by Alexowo** [pablouser1/ProxiTok#8]
At the moment when you download a video through this site it downloads as "tiktok-video.mp4" — I personally feel like it'd be better if the username or the video ID was added to the file name or metadata, maybe the date in metadata as well?

The fact that the watermark downloads is nice though, maybe that could be turned off somehow? Since websites like https://ssstik.io/ download without a watermark.

**Comment by pablouser1** [comment]
> I had to use one of those web services because I couldn't find updated info on how to get the url

Nevermind, it's now working without having to use any external service
