### ISSUE TITLE
[INSTANCES] New public instance

### ISSUE THREAD

**Issue by ManaSiWibi** [pablouser1/ProxiTok#82]
- URL: https://proxitok.manasiwibi.com/ and http://vywqfflneajejuhg7o5iklqvzemu2fcdrb3gtkvnyqsho6qin5svdsad.onion
- Cloudflare: No
- Country: Singapore

**Comment by pablouser1** [comment]
Hi @ManaSiWibi, thanks for hosting a public instance! It has been added to the public instances list.

**Comment by ManaSiWibi** [comment]
@pablouser1 Unfortunately, I'm no longer maintaining this instance. Kindly delete from the instances list, thank you.
