### ISSUE TITLE
Are bots ok?

### ISSUE THREAD

**Issue by k2helix** [pablouser1/ProxiTok#84]
Hi. I discovered Proxitok a while ago and thought about making a bot that would scrape a proxitok instance and send someone's posts into Discord. It would just scrape it when a Discord user requests (via a command) to see a tiktok profile (which would not happen so much).

Is this ok or do you prefer not to let bots scrape proxitok instances? I'm asking because as you may know one of the causes of Bibliogram dying was the bots that were scraping it.

**Comment by pablouser1** [comment]
Hi @k2helix,

Bots/automated requests are a growing problem in ProxiTok. I guess it's OK if you don't spam requests, but I would still _highly_ appreciate anyone trying to scrape ProxiTok not to. There are already libraries such as [TikTok-Api](https://github.com/davidteather/TikTok-Api) for Python or [tiktok-scraper](https://github.com/drawrowfly/tiktok-scraper) for JS/TS, to name a few, that do the job for you.

> I'm asking because as you may know one of the causes of Bibliogram dying was the bots that were scraping it.

I wasn't aware about Bibliogram been discotinued... I've been reading [Bibliogram's author blog article](https://cadence.moe/blog/2022-09-01-discontinuing-bibliogram) about it.
ProxiTok is having similar problems with bots spamming requests non-stop (at a smaller scale though, this project is still relatively young after all).

RSS isn't much of a problem (at least for now). All requests made to TikTok are cached for some time so they don't impact that much rate limits.
