### ISSUE TITLE
always returns API error code -1 (UNKNOWN_ERROR)

### ISSUE THREAD

**Issue by alectprasad** [pablouser1/ProxiTok#85]
web version (https://proxitok.herokuapp.com/) always returns API error code -1 (UNKNOWN_ERROR) with any url

**Comment by NoPlagiarism** [comment]
You are using old verison
Use [proxitok.pabloferreiro.es](https://proxitok.pabloferreiro.es/)

**Comment by NoPlagiarism** [comment]
@pablouser1 should you make a disclamer or redirector?

**Comment by pablouser1** [comment]
> @pablouser1 should you make a disclamer or redirector?

I thought that instance wasn't used anymore, but I just checked the logs and I'm still getting many requests there. I'll redirect all requests to a disclaimer with the new instance, hopefully that fixes the issue.
