### ISSUE TITLE
Keep original og:meta properties, so ProxiTok has a nice preview like the original.

### ISSUE THREAD

**Issue by pcroland** [pablouser1/ProxiTok#88]
This would make it possible to remove the original message from Telegram/Discord and having a preview too:
![img](https://telegra.ph//file/4a3f12acec4ff5e6cafbc.png)

**Comment by pablouser1** [comment]
Hi! Thanks to 215f984fe4f5dd3736fd882f96c851eac5317cf3 now ProxiTok mirrors the `og:...` and the `twitter:...`  meta tags.
Here's an example on Discord:

![Preview](https://user-images.githubusercontent.com/17802865/204111910-b47a95a8-6b3c-4ea1-9929-4c554e21c80d.png)

**Comment by pcroland** [comment]
Really nice, thanks.
