### ISSUE TITLE
[INSTANCES] New public instance: tt.vern.cc

### ISSUE THREAD

**Issue by gi-yt** [pablouser1/ProxiTok#89]
- URL: https://tt.vern.cc
- Cloudflare: No
- Country: Canada
- I2P:  http://vern2gwxbtxzhb3rgchv4kbhlqppijhjqg7rmgvp4c5bxihxcm3a.b32.i2p
- Tor: http://tt.vernccvbvyi5qhfzyqengccj7lkove6bjot2xhh5kajhwvidqafczrad.onion

**Comment by NoPlagiarism** [comment]
### Isn't this [i2p](http://vernz3ubrntql4wrgyrssd6u3qzi36zrhz2agbo6vibzbs5olk2q.b32.i2p/) an libremdb?
![IMDB screenshot (http://vernz3ubrntql4wrgyrssd6u3qzi36zrhz2agbo6vibzbs5olk2q.b32.i2p/ url)](https://user-images.githubusercontent.com/37241775/198827839-9945c930-04a8-48ec-938f-0d78f427bc3a.png)

### Also [onion](http://ld.vernccvbvyi5qhfzyqengccj7lkove6bjot2xhh5kajhwvidqafczrad.onion/) too
![IMDB screenshot (http://ld.vernccvbvyi5qhfzyqengccj7lkove6bjot2xhh5kajhwvidqafczrad.onion/ url)](https://user-images.githubusercontent.com/37241775/198828063-5fe4af3c-8363-459e-9aed-9d59e71ebdf5.png)

**Comment by gi-yt** [comment]
sorry for that, pasted wrong link
tt.vernccvbvyi5qhfzyqengccj7lkove6bjot2xhh5kajhwvidqafczrad.onion
vern2gwxbtxzhb3rgchv4kbhlqppijhjqg7rmgvp4c5bxihxcm3a.b32.i2p
these are the right links @NoPlagiarism

**Comment by NoPlagiarism** [comment]
Edit original issue, pls

**Comment by NoPlagiarism** [comment]
```MarkDown
# I2P
| URL |
| :---: |
| [vern2gwxbtxzhb3rgchv4kbhlqppijhjqg7rmgvp4c5bxihxcm3a.b32.i2p](http://vern2gwxbtxzhb3rgchv4kbhlqppijhjqg7rmgvp4c5bxihxcm3a.b32.i2p) |
```

To add in [Wiki instances](https://github.com/pablouser1/ProxiTok/wiki/Public-instances)

**Comment by pablouser1** [comment]
Hi @gi-yt, thanks for hosting a public instance! It has been added to the public instances list.

**Comment by gi-yt** [comment]
@pablouser1 can you move the instance country from Canada to US since we moved the VPS.. 
Thanks

**Comment by pablouser1** [comment]
Moved!
