### ISSUE TITLE
[INSTANCES] New public instance

### ISSUE THREAD

**Issue by NyeUsr** [pablouser1/ProxiTok#92]
Not my instance. Just an instance I found which is available to the public.

- URL: https://proxitok.mha.fi
- Cloudflare: Yes (https://bgp.he.net/dns/mha.fi)
- Country: France (https://bgp.he.net/ip/51.158.61.247#_whois)

**Comment by NoPlagiarism** [comment]
Can't watch any video. Browser trying to access video and sth (mb CloudFlare?) blocking it

![CloudFlare in 302 Response Headers](https://user-images.githubusercontent.com/37241775/200660572-ac58d0a8-f752-41b3-ac8c-a777afe3e8c1.png)

**Comment by NyeUsr** [comment]
My bad for not checking more into that. I thought it was just my phone as a friend said he'd had luck with it. I've contacted the website owner in regards to the issue.

**Comment by NoPlagiarism** [comment]
Now it just going like
```
There was an error processing your request!

HTTP Code: 503

API error code 10 (CURL_ERROR) 
```

**Comment by NoPlagiarism** [comment]
> Can't watch any video

Video is watchable now

**Comment by pablouser1** [comment]
@NyeUsr Thanks for hosting a public instance! It has been added to the list.
