### ISSUE TITLE
Show date when viewing from a link

### ISSUE THREAD

**Issue by MilkaPeeka** [pablouser1/ProxiTok#93]
**Is your feature request related to a problem? Please describe.**
No, I don't have any problem using ProxiTok, and it is not a mandatory feature at all, but since it exists on other pages (For example: When you view a user video from his profile), the date exists.

**Describe the solution you'd like**
There's no visible upload date when you open ProxiTok from a link, but there is one when I view the user from his profile page,
so I think a simple solution will just be showing the date when I view a video from a link, perhaps next to the "views, likes, comments"

**Describe alternatives you've considered**
I could view the date from the user profile, and I will probably continue to do so if it's too difficult to implement or not to be implemented.

**Comment by pablouser1** [comment]
I really don't know I didn't implement it in the first place, but now it is. Thanks for pointing it out!
