### ISSUE TITLE
error on click next button for user videos

### ISSUE THREAD

**Issue by salman731** [pablouser1/ProxiTok#96]
**About this instance**

Frontend version: 2.4.3.0

Scraper version: 2.3.2.1

When I search user and click next button for next videos error occur...

![proxitok](https://user-images.githubusercontent.com/25194088/201509814-c451ea7c-7633-478f-bf2e-33e3e4b9e3d8.PNG)

**Comment by NoPlagiarism** [comment]
Duplicate of #94
