### ISSUE TITLE
[INSTANCES] Add onion version of tok.habedieeh.re

### ISSUE THREAD

**Issue by shruuub** [pablouser1/ProxiTok#99]
- URL: http://tok.habeehrhadazsw3izbrbilqajalfyqqln54mrja3iwpqxgcuxnus7eid.onion/
- Cloudflare: No
- Country: CA

yeah, I think I forgot it in the original issue, but here's the hidden service of tok.habedieeh.re. Really like how the project's going, keep it up :)!

**Comment by pablouser1** [comment]
Added, thanks!
